---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - MMatlacz
      - skarzi
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - MMatlacz
      - skarzi
