---
language: python
python:
  - 3.7
  - 3.8
env:
  - POETRY_VERSION=1.0.0
before_install:
  - python --version
  - pip freeze | xargs pip uninstall -y
  - pip install poetry==${POETRY_VERSION}
install:
  - poetry install
script:
  - pytest  # run tests
  - poetry check  # validate `pyproject.toml`
after_success:
  - pip install codecov
  - codecov  # submit coverage
notifications:
  email:
    on_success: never
    on_failure: change
