---
dist: xenial
os: linux
language: python
python:
  - 3.7
  - 3.8
env:
  - POETRY_VERSION=1.0.0
before_install:
  - pip freeze | xargs pip uninstall -y
  - pip install poetry==${POETRY_VERSION}
install:
  - poetry install
script:
  - make test
after_success:
  - pip install codecov
  - codecov  # submit coverage
notifications:
  email:
    on_success: never
    on_failure: change
