[tool.poetry]
name = "location_extractor"
version = "1.0.0"
description = "Extract countries, regions and cities from text"
# TODO: add authors
authors = []
license = "MIT"
include = [
    "location_extractor/data/*.csv",
    "location_extractor/data/*.db",
]
readme = "README.md"
repository = "https://github.com/MMatlacz/LocationExtractor"
# TODO: add classifiers
classifiers = [
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
numpy = "^1.18.2"
nltk = "^3.4.5"
jellyfish = "^0.7.2"
pycountry = "^19.8.18"
pandas = "^1.0.3"
Unidecode = "^1.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
pytest-cov = "^2.8.1"
ipython = "^7.13.0"
isort = "^4.3.21"
pytest-isort = "^0.3.1"
wily = "^1.16.0"
safety = "^1.8.7"
wemake-python-styleguide = "^0.14.0"
flake8-pytest-style = "^1.0.0"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
