[tool.poetry]
name = "location_extractor"
version = "1.0.0"
description = "Extract countries, regions and cities from text"
# TODO: add authors
authors = []
license = "MIT"
include = [
    "location_extractor/data/*.csv",
]
readme = "README.md"
repository = "https://github.com/MMatlacz/LocationExtractor"
# TODO: add classifiers
classifiers = [
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
numpy = "^1.18.4"
nltk = "^3.5"
jellyfish = "^0.7.2"
pycountry = "^19.8.18"
Unidecode = "^1.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
pytest-cov = "^2.9.0"
ipython = "^7.14.0"
isort = "^4.3.21"
pytest-isort = "^1.0.0"
wily = "^1.16.0"
safety = "^1.9.0"
wemake-python-styleguide = "^0.14.0"
flake8-pytest-style = "^1.0.0"
pytest-deadfixtures = "^2.2.0"
pytest-randomly = "^3.3.1"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
